name: Workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Install modules
      - name: Install modules
        run: yarn install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Run linters
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run solhint
        run: ./node_modules/.bin/solhint contracts/interfaces/*.sol contracts/*.sol contracts/test/*.sol

      # Compile the code
      - name: Clean hardhat in order to avoid the solc checksum verification failure
        run: ./node_modules/.bin/hardhat clean --global
      - name: Compile, adjust uniswap library hash and recompile again
        run: npm run compile

      # Compile the code and run hardhat tests
      - name: Run hardhat tests
        run: ./node_modules/.bin/hardhat test

      # Compile the code and run foundry tests
      - name: Run foundry tests
        run: forge test --hh -vvv

      # Run hardhat coverage and upload codecov report
      - name: Solidity coverage summary
        run: ./node_modules/.bin/hardhat coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
